# Generated by Django 3.2.4 on 2021-06-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referralDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
