# Generated by Django 3.2.4 on 2021-06-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_auto_20210626_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referralDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
