# Generated by Django 3.2.4 on 2021-06-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_auto_20210626_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
