# Generated by Django 3.2.4 on 2021-06-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0004_auto_20210626_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referralDate',
            field=models.DateField(null=True),
        ),
    ]
